services:
  copfront:
    build:
      context: /home/mema/code/copertinefull/frontend
    image: copfront:0.1.0
    container_name: copfront
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - ENV WEAVIATE_SCHEME=http
      - ENV WEAVIATE_HOST=weaviate:8080
      - ENV WEAVIATE_COLLECTION=Copertine
    ports:
      - "3737:3000"
    volumes:
      - /home/mema/code/copertinefull/images:/images:ro  # Read-only
    command: ["node", "server.js"]
    networks:
      - mema_network
      - weaviate_net
    restart: unless-stopped

  copback:
    build:
      context: /home/mema/code/copertinefull/backend
    image: copback:0.1.0
    container_name: copback
    ports:
      - "8383:8383"
    volumes:
      - /home/mema/code/copertinefull/images:/app/images  # Read-write
    networks:
      - mema_network
      - weaviate_net
    restart: unless-stopped
