[tool.poetry]
name = "copertine3"
version = "0.1.0"
description = ""
authors = ["Robert Alexander <gogonegro@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.59.3"
together = "^1.3.11"
python-dotenv = "^1.0.1"
beautifulsoup4 = "^4.12.3"
weaviate-client = "^4.10.2"
pydantic = "^2.10.4"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
