[tool.poetry]
name = "copertine3"
version = "0.1.0"
description = ""
authors = ["Robert Alexander <gogonegro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.59.3"
together = "^1.3.11"
python-dotenv = "^1.0.1"
beautifulsoup4 = "^4.12.3"
weaviate-client = "^4.10.2"
pydantic = "^2.10.4"
requests = "^2.32.3"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.6"
mypy = "^1.14.1"
types-beautifulsoup4 = "^4.12.0.20241020"
types-requests = "^2.32.0.20241016"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
