# Same as Black.
line-length = 88

# Assume Python 3.10
target-version = "py310"

[lint]
# Enable flake8-bugbear (`B`) rules.
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "C",   # mccabe complexity
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
    "TRY", # tryceratops
    "PLR", # pylint refactor
]

# Never enforce `E501` (line length violations).
ignore = ["E501"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.mccabe]
# Flag errors (`C901`) when complexity exceeds 10.
max-complexity = 10

[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"**/tests/**" = ["PLR2004"]

[lint.isort]
combine-as-imports = true
